---
apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: metacollector
spec:
  component:
    type: metacollector
  replicas: 1
  podTemplateSpec:
    spec:
      containers:
        - name: metacollector
          resources:
            requests:
              cpu: 3m
              memory: 32Mi
            limits:
              memory: 64Mi
