---
apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: sidekick-ui
spec:
  component:
    type: falcosidekick-ui
  replicas: 1
  podTemplateSpec:
    spec:
      initContainers:
        - name: wait-redis
          env:
            - name: REDIS_ADDR
              value: "falco-valkey:6379"
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 32Mi
      containers:
        - name: falcosidekick-ui
          args:
            - "-r"
            - "falco-valkey:6379"
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              memory: 128Mi
