---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: litellm-database
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-database
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-database
        property: password
