---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: litellm-secrets
  data:
    - secretKey: masterkey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-keys
        property: masterkey
