---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: litellm-secrets-env
  data:
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-database
        property: salt_key
