---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: litellm-oidc
  data:
    - secretKey: GENERIC_AUTHORIZATION_ENDPOINT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: authz_url
    - secretKey: GENERIC_TOKEN_ENDPOINT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: token_url
    - secretKey: GENERIC_USERINFO_ENDPOINT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: user_info_url
    - secretKey: GENERIC_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-oidc
        property: client_id
    - secretKey: GENERIC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-oidc
        property: client_secret
