---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ./configmap.yaml
  - ./external-secret-cloudnativepg-barman-credentials.yaml
  - ./external-secret-database.yaml
  - ./external-secret-oidc.yaml
  - ./external-secret-secrets-env.yaml
  - ./external-secret-secrets.yaml
  - ./postgresql.yaml
  - ./postgresql-objectstore-scaleway.yaml
  - ./postgresql-backup.yaml
