---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2
spec:
  blocks:
    - start: 10.100.70.1
      stop: 10.100.79.255
    - start: 2a01:4f8:121:14e2:100:3:1:1
      stop: 2a01:4f8:121:14e2:100:3:10:255
  serviceSelector:
    matchLabels:
      loadbalancer/pool: l2
  disabled: false
