---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: kgateway-gateway-service-parameters
spec:
  kube:
    service:
      type: LoadBalancer
      loadBalancerClass: "${KGATEWAY_LB_CLASS}"
      extraAnnotations:
        ${KGATEWAY_IP_ANNOTATION}: "${KGATEWAY_IP}"
