---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: global-http-listener-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kgateway-gateway
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kgateway-gateway-internal
  upgradeConfig:
    enabledUpgrades:
      - websocket
