---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - gateway-service-parameters.yaml
  - gateway.yaml
  - global-https-redirect.yaml
  # - global-hsts.yaml
  - fallback-to-traefik.yaml
