---
fullnameOverride: victoria-logs

serviceAccount:
  create: true

server:
  extraArgs:
    envflag.enable: true
    envflag.prefix: VM_
    loggerFormat: json
    httpListenAddr: :9428
    http.shutdownDelay: 15s
    retentionPeriod: 3d
    retention.maxDiskUsagePercent: "85"
  persistentVolume:
    storageClassName: ${DEFAULT_STORAGE_CLASS}
    size: 20Gi
  service:
    type: ClusterIP
    clusterIP: ""
    ipFamilyPolicy: PreferDualStack
  resources:
    requests:
      cpu: 30m
      memory: 512Mi
    limits:
      memory: 768Mi

dashboards:
  enabled: true
  labels:
    grafana_dashboard: "1"
