---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &application landing-page-internal
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: cluster-applications
  path: ./sites/vie/applications/landing-page/internal/app/
  interval: 10m
  retryInterval: 2m
  prune: true
  force: false
  wait: false
  postBuild:
    substitute:
      APPLICATION: *application
      APPLICATION_NAMESPACE: landing-page
      GATEWAY_NAME: kgateway-gateway-internal
      PARENT_DOMAIN: ${LOCAL_INTERNAL_DOMAIN}
      EXTERNAL_DNS_PROVIDER: internal
      CLUSTER_ISSUER: ${INTERNAL_CLUSTER_ISSUER}
