---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: dex-config
    template:
      engineVersion: v2
      data:
        config.yaml: |-
          issuer: https://auth.${PUBLIC_DOMAIN}/api/dex
          oauth2:
            skipApprovalScreen: true
          storage:
            type: memory
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: {{ .github_client_id }}
                clientSecret: {{ .github_client_secret }}
                redirectURI: https://auth.${PUBLIC_DOMAIN}/api/dex/callback
                teamNameField: slug
                orgs:
                  - name: fhburgenland-bswe
          staticClients:
            - id: argo-cd
              secret: {{ .argocd_client_secret }}
              name: ArgoCD
              redirectURIs:
                - https://argocd.${PUBLIC_DOMAIN}/api/dex/callback
            - id: registry
              secret: {{ .registry_client_secret }}
              name: Registry
              redirectURIs:
                - https://registry.${PUBLIC_DOMAIN}/zot/auth/callback/oidc
                - https://registry.${PUBLIC_DOMAIN}/c/oidc/callback
  data:
    - secretKey: github_client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex-github
        property: client_id
    - secretKey: github_client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex-github
        property: client_secret
    - secretKey: argocd_client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex-argocd
        property: client_secret
    - secretKey: registry_client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex-registry
        property: client_secret
