---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  settings.yaml: |-
    instanceName: internal
    title: Tuxnet

    language: en

    theme: dark
    color: slate
    iconStyle: theme
    fullWidth: false
    useEqualHeights: true
    headerStyle: clean

    target: _blank

    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: false
      hideVisitURL: true
      provider: google

    hideVersion: true
    disableUpdateCheck: true
    disableIndexing: true

    layout:
      Lifestyle:
        style: row
        columns: 2
      AI:
        style: row
        columns: 2
      Home Automation:
        style: row
        columns: 3
      Monitoring:
        style: row
        columns: 2
      Network:
        style: row
        columns: 2
  services.yaml: ""
  widgets.yaml: ""
  bookmarks.yaml: ""
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
