---
toolbox:
  enabled: true
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      memory: 256Mi

cephImage:
  repository: quay.io/ceph/ceph
  tag: v21.1.0
  allowUnsupported: false

cephClusterSpec:
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  cleanupPolicy:
    confirmation: "" # "yes-really-destroy-data"
  disruptionManagement:
    managePodBudgets: false
  cephConfig:
    global:
      osd_pool_default_size: "2"
      osd_pool_default_min_size: "1"
      mon_warn_on_pool_no_redundancy: "false"
      bdev_flock_retry: "20"
      bluefs_buffered_io: "false"
      mon_data_avail_warn: "10"
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
    modules:
      - name: pg_autoscaler
        enabled: true
      - name: rook
        enabled: false
  dashboard:
    enabled: true
    ssl: false
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "^sd[bc]"
  priorityClassNames:
    all: system-node-critical
  resources:
    mgr:
      requests:
        cpu: 66m
        memory: 1171Mi
      limits:
        memory: 1171Mi
    mon:
      requests:
        cpu: 59m
        memory: 594Mi
      limits:
        memory: 1024Mi
    osd:
      requests:
        cpu: 150m
        memory: 2560Mi
      limits:
        memory: 4096Mi
    # prepareosd: # not set
    # mgr-sidecar: # not set
    crashcollector:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        memory: 96Mi
    logcollector:
      requests:
        cpu: 3m
        memory: 8Mi
      limits:
        memory: 16Mi
    # cleanup # not set
    exporter:
      requests:
        cpu: 15m
        memory: 32Mi
      limits:
        memory: 64Mi

cephBlockPools:
  - name: builtin-mgr
    spec:
      name: .mgr
      failureDomain: osd
      replicated:
        size: 2
        requireSafeReplicaSize: false
      parameters:
        compression_mode: none
      mirroring:
        enabled: false
    storageClass:
      enabled: false
  - name: ceph-pool
    spec:
      failureDomain: osd
      replicated:
        size: 2
        requireSafeReplicaSize: false
      parameters:
        compression_mode: aggressive
      mirroring:
        enabled: false
    storageClass:
      enabled: true
      provisioner: rook-ceph.rbd.csi.ceph.com
      name: rook-ceph-block
      isDefault: true
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      parameters:
        imageFormat: "2"
        imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-publish-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-modify-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-modify-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-publish-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-publish-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4

cephFileSystems: []

cephObjectStores: []
