---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: harbor-secrets
  data:
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: jobservice-secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: registry-secret
    - secretKey: CSRF_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: csrf-key
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: registry-password
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: registry-htpasswd
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: communication-secret
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor
        property: encryption-secret
