---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scaleway-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: scaleway-credentials
  data:
    - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: registry-scaleway
        property: access_key
    - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: registry-scaleway
        property: secret_key
