---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: harbor-secrets
  data:
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-jobservice
        property: secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-registry
        property: secret
    - secretKey: CSRF_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-csrf
        property: key
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-communication
        property: secret
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-encryption
        property: secret
