---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-logs-grafana-ds
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    ---
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        isDefault: false
        url: http://victoria-logs-server.victoria-logs:9428
        jsonData:
          multitenancyHeaders:
            AccountID: "0"
            ProjectID: "0"
