---
extraArgs:
  - "--config.file=/config/snmp.yml"

extraSecretMounts:
  - name: config
    mountPath: /config
    secretName: snmp-config
    readOnly: true
    defaultMode: 420

service:
  ipDualStack:
    enabled: true

configmapReload:
  enabled: true
  extraArgs:
    - "--watched-dir=/config"
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true

resources:
  requests:
    cpu: 3m
    memory: 24Mi
  limits:
    memory: 24Mi
