---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-controller-mongodb-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: omada-controller-mongodb-user
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        uri: "mongodb://omada:{{ .password }}@omada-controller-mongodb-rs0:27017/omada?replicaSet=rs0&authSource=omada"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: omada-controller-mongodb-user
        property: password
