---
replicaCount: 1
numWorkers: 1

strategy:
  type: Recreate

extraEnvVars:
  - name: LITELLM_MODE
    value: "PRODUCTION"
  - name: DOCS_URL
    value: "/docs"
  - name: ROOT_REDIRECT_URL
    value: "/ui"
  - name: PROXY_BASE_URL
    value: "https://litellm.${LOCAL_INTERNAL_DOMAIN}"
  - name: ALLOWED_EMAIL_DOMAINS
    value: "muehlbachler.io"
  - name: GENERIC_SCOPES
    value: "openid email profile"
  - name: PROXY_ADMIN_ID
    value: "litellm-proxy-admin"
  - name: GENERIC_USER_ID_ATTRIBUTE
    value: "preferred_username"
  - name: GENERIC_USER_EMAIL_ATTRIBUTE
    value: "email"
  - name: GENERIC_USER_DISPLAY_NAME_ATTRIBUTE
    value: "name"
  - name: GENERIC_USER_FIRST_NAME_ATTRIBUTE
    value: "given_name"
  - name: GENERIC_USER_LAST_NAME_ATTRIBUTE
    value: "family_name"
  - name: GENERIC_USER_ROLE_ATTRIBUTE
    value: "grants"

environmentSecrets:
  - litellm-secrets-env
  - litellm-oidc

masterkeySecretName: litellm-secrets-env
masterkeySecretKey: LITELLM_MASTER_KEY

proxyConfigMap:
  create: false
  name: litellm-config
  key: config.yaml

db:
  useExisting: true
  deployStandalone: false
  endpoint: litellm-postgresql-rw
  database: litellm
  secret:
    name: litellm-database
    usernameKey: username
    passwordKey: password

redis:
  enabled: false

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

migrationJob:
  enabled: false # also sets env vars for main container which then sets DISABLE_SCHEMA_UPDATE twice on the migration job
  hooks:
    argocd:
      enabled: false
    helm:
      enabled: true

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "${INTERNAL_CLUSTER_ISSUER}"
    external-dns.alpha.kubernetes.io/provider: internal
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: &domain litellm.${LOCAL_INTERNAL_DOMAIN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: litellm-tls-cert
      hosts:
        - *domain

resources:
  requests:
    cpu: 10m
    memory: 768Mi
  limits:
    memory: 1536Mi
