---
installCRDs: true

extraArgs:
  - "--dns01-recursive-nameservers-only"
  - "--dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53"

config:
  enableGatewayAPI: true
  enableGatewayAPIListenerSet: true
  featureGates:
    ListenerSets: true

serviceIPFamilyPolicy: PreferDualStack
serviceAnnotations:
  gatus.home-operations.com/enabled: "true"

webhook:
  serviceIPFamilyPolicy: PreferDualStack
  resources:
    requests:
      cpu: 3m
      memory: 72Mi
    limits:
      memory: 72Mi

cainjector:
  resources:
    requests:
      cpu: 3m
      memory: 125Mi
    limits:
      memory: 125Mi

resources:
  requests:
    cpu: 3m
    memory: 113Mi
  limits:
    memory: 113Mi
