---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    storage:
      type: sqlite
      path: /data/data.db

    ui:
      title: Status Dashboard
      description: The current service status of the muehlbachler organization, specifically to the MUC site.
      header: Health Status
      default-sort-by: name

    alerting:
      ntfy:
        url: https://notify.infrastructure.muehlbachler.io
        topic: ${NTFY_TOPIC}
        token: ${NTFY_TOKEN}
        priority: 2
        click: https://status.${LOCAL_HOME_DOMAIN}
        default-alert:
          description: site ${SITE}
          send-on-resolved: true
          failure-threshold: 6
          success-threshold: 3

    endpoints:
      # External - Mail
      - name: IMAP (Soverin)
        group: External - Mail
        url: tls://imap.soverin.net:993
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
          - "[CERTIFICATE_EXPIRATION] > 48h"
        alerts:
          - type: ntfy
            priority: 4
      - name: SMTP Outgoing (Soverin)
        group: External - Mail
        url: tls://smtp.soverin.net:465
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
          - "[CERTIFICATE_EXPIRATION] > 48h"
        alerts:
          - type: ntfy
            priority: 4
      - name: SMTP Incoming (Soverin)
        group: External - Mail
        url: tcp://mx.soverin.net:25
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: ntfy
            priority: 4
      - name: IMAP
        group: External - Mail
        url: tls://mail.muehlbachler.io:993
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
          - "[CERTIFICATE_EXPIRATION] > 48h"
        alerts:
          - type: ntfy
            priority: 4
      - name: SMTP Outgoing
        group: External - Mail
        url: tls://mail.muehlbachler.io:465
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
          - "[CERTIFICATE_EXPIRATION] > 48h"
        alerts:
          - type: ntfy
            priority: 4
      - name: SMTP Incoming
        group: External - Mail
        url: tcp://mail.muehlbachler.io:25
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: ntfy
            priority: 4
      - name: SimpleLogin Aliases
        group: External - Mail
        url: https://aliases.email.muehlbachler.io/auth/login
        method: GET
        interval: 5m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: ntfy
            priority: 3
      # External - Infrastructure
      - name: AdGuard Home
        group: External - Infrastructure
        url: udp://10.1.71.10:53
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: ntfy
            priority: 5
      - name: Vault
        group: External - Infrastructure
        url: https://vault.platform.muehlbachler.io:8200/ui/
        interval: 5m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: ntfy
            priority: 5
      - name: ntfy
        group: External - Infrastructure
        url: https://notify.infrastructure.muehlbachler.io
        interval: 5m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: ntfy
            priority: 5
      - name: VPN
        group: External - Infrastructure
        url: https://vpn.platform.muehlbachler.io/
        interval: 5m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: ntfy
            priority: 5
