---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-scaleway-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: scaleway-credentials
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "access_key": "{{ .access_key }}",
            "secret_key": "{{ .secret_key }}",
            "project_id": "{{ .project_id }}",
            "organization_id": "{{ .organization_id }}",
            "region": "fr-par",
            "zone": "fr-par-1"
          }
  data:
    - secretKey: access_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: crossplane-scaleway
        property: access_key
    - secretKey: secret_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: crossplane-scaleway
        property: secret_key
    - secretKey: project_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: crossplane-scaleway
        property: project_id
    - secretKey: organization_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: crossplane-scaleway
        property: organization_id
