---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-organization-application
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: github-organization-application
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://github.com/fhburgenland-bswe
        githubAppID: "{{ .app_id }}"
        githubAppInstallationID: "{{ .installation_id }}"
        githubAppPrivateKey: |
          {{ .private_key | replace "\\n" "\n" | nindent 4 }}
  data:
    - secretKey: app_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-app
        property: app_id
    - secretKey: installation_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-app
        property: organization_installation_id
    - secretKey: private_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: github-app
        property: private_key
