---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-application
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: github-application
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: app_id
      remoteRef:
        key: github-app
        property: app_id
    - secretKey: muhlba91_installation_id
      remoteRef:
        key: github-app
        property: muhlba91_installation_id
    - secretKey: organization_installation_id
      remoteRef:
        key: github-app
        property: organization_installation_id
    - secretKey: private_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: github-app
        property: private_key
