---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ./external-secret-argocd-oidc.yaml
  - :/external-secret-github-application.yaml
  - ./external-secret-github-muhlba91-application.yaml
  - ./external-secret-github-organization-application.yaml
  - ./repository-apps.yaml
  - ./application-app-of-apps.yaml
  - ./gateway-server.yaml
  - ./gateway-applicationset.yaml
  # - ./external-secret-registry-credentials.yaml
