---
fullnameOverride: kgateway

controller:
  replicaCount: 1
  extraEnv:
    KGW_ENABLE_GATEWAY_API_EXPERIMENTAL_FEATURES: "true"

resources:
  requests:
    cpu: 5m
    memory: 256Mi
  limits:
    memory: 256Mi
