---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: falco-rules-exceptions
  namespace: falco
spec:
  inlineRules:
    - rule: Drop and execute new binary in container
      exceptions:
        - name: cilium_cni_binary_install
          fields: [proc.name, proc.exepath]
          comps: [=, =]
          values:
            - - cilium-cni
              - /opt/cni/bin/cilium-cni
        - name: homeassistant_backup_and_sops
          fields: [container.image.repository, container.name, k8s.ns.name]
          comps: [=, =, startswith]
          values:
            - - docker.io/library/alpine
              - backup
              - home-assistant-
            - - docker.io/library/alpine
              - backup-restore
              - home-assistant-
            - - docker.io/library/python
              - backup
              - home-assistant-
            - - ghcr.io/home-assistant/home-assistant
              - home-assistant
              - home-assistant-
        - name: agents_init_provisioning
          fields: [container.image.repository, container.name, k8s.ns.name]
          comps: [=, =, startswith]
          values:
            - - docker.io/library/alpine
              - init
              - agents
        - name: telegraf_entrypoint_binary
          fields: [container.image.repository, container.name, proc.name]
          comps: [=, =, =]
          values:
            - - docker.io/library/telegraf
              - telegraf
              - telegraf
      override:
        exceptions: append
    - rule: Fileless execution via memfd_create
      exceptions:
        - name: nvidia_ctk_ldconfig_hook
          fields: [proc.pname, proc.exepath]
          comps: [=, startswith]
          values:
            - - nvidia-ctk
              - "memfd:runc_cloned:/run/nvidia-ctk-hook/"
      override:
        exceptions: append
    - rule: Terminal shell in container
      exceptions:
        - name: rook_ceph_logrotate_sidecar
          fields: [container.image.repository, container.name, k8s.ns.name]
          comps: [=, =, =]
          values:
            - - quay.io/ceph/ceph
              - log-collector
              - rook-ceph
      override:
        exceptions: append
    - rule: Packet socket created in container
      exceptions:
        - name: homeassistant_dhcp_discovery
          fields: [container.image.repository, container.name, proc.name]
          comps: [=, =, =]
          values:
            - - ghcr.io/home-assistant/home-assistant
              - home-assistant
              - python3
      override:
        exceptions: append
    - rule: Create Hardlink Over Sensitive Files
      exceptions:
        - name: samba_adduser_provisioning
          fields: [container.image.repository, container.name, proc.name]
          comps: [=, =, =]
          values:
            - - ghcr.io/crazy-max/samba
              - samba
              - adduser
      override:
        exceptions: append
  priority: 51
