---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-configuration
data:
  # cluster configuration
  SITE: hochschule-burgenland
  CILIUM_CLUSTER_ID: "1"

  # network configuration
  NODE_IP: "10.100.50.1"
  ROUTER_IP: "10.100.0.1"

  # domain names
  PUBLIC_DOMAIN: hochschule-burgenland.muehlbachler.xyz
  LOCAL_PUBLIC_DOMAIN: hochschule-burgenland.muehlbachler.xyz
  INTERNAL_DOMAIN: internal.muehlbachler.xyz
  LOCAL_INTERNAL_DOMAIN: hochschule-burgenland.internal.muehlbachler.xyz

  # cluster issuers
  PUBLIC_CLUSTER_ISSUER: cluster-issuer-muehlbachler-xyz
  INTERNAL_CLUSTER_ISSUER: cluster-issuer-muehlbachler-xyz

  # CIDRs
  CILIUM_IPV4_POD_CIDR: "10.102.0.0/16"
  CILIUM_IPV6_POD_CIDR: "fc00:db8:102::/112"

  # load balancer
  METALLB_LB_CLASS: "io.metallb/load-balancer"
  METALLB_IP_ANNOTATION: "metallb.io/loadBalancerIPs"
  CILIUM_LB_CLASS: "io.cilium/bgp-control-plane"
  CILIUM_L2_LB_CLASS: "io.cilium/l2-announcer"
  CILIUM_IP_ANNOTATION: "lbipam.cilium.io/ips"
  # kgateway specific load balancer
  KGATEWAY_INTERNAL_LB_CLASS: "io.cilium/l2-announcer"
  KGATEWAY_INTERNAL_IP_ANNOTATION: "lbipam.cilium.io/ips"
  KGATEWAY_EXTERNAL_LB_CLASS: "io.cilium/l2-announcer"
  KGATEWAY_EXTERNAL_IP_ANNOTATION: "lbipam.cilium.io/ips"
  # traefik specific load balancer
  TRAEFIK_LB_CLASS: "io.cilium/l2-announcer"
  TRAEFIK_IP_ANNOTATION: "lbipam.cilium.io/ips"
  # ip addresses for services
  TRAEFIK_IP: "10.100.72.3,2a01:4f8:121:14e2:100:3:3:3"
  KGATEWAY_INTERNAL_IP: "10.100.72.1,2a01:4f8:121:14e2:100:3:3:1"
  KGATEWAY_EXTERNAL_IP: "10.100.72.2,2a01:4f8:121:14e2:100:3:3:2"

  # public ip addresses
  PUBLIC_IP: "178.63.69.250,2a01:4f8:121:14e2:100:3:3:2"

  # storage classes
  DEFAULT_STORAGE_CLASS: "rook-ceph-block"
