---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp-server-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: github-mcp-server-secrets
  data:
    - secretKey: GITHUB_PERSONAL_ACCESS_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-mcp-server-github
        property: access-token
