---
image:
  repository: ollama/ollama
  tag: 0.21.2

runtimeClassName: nvidia

${APPLICATION}:
  gpu:
    enabled: true
    type: nvidia
    nvidiaResource: nvidia.com/gpu
    number: 1
  models:
    pull:
      # https://github.com/allenporter/home-assistant-datasets/tree/main/reports
      - qwen3.5:9b-q4_K_M
      - gemma4:e2b-it-q4_K_M

extraEnv:
  - name: OLLAMA_MAX_LOADED_MODELS
    value: "2"
  - name: OLLAMA_NUM_PARALLEL
    value: "2"
  - name: OLLAMA_KEEP_ALIVE
    value: "1"
  - name: OLLAMA_CONTEXT_LENGTH
    value: "16384"

service:
  annotations:
    gatus.home-operations.com/enabled: "true"

ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: "${INTERNAL_CLUSTER_ISSUER}"
    external-dns.alpha.kubernetes.io/provider: internal
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: &domain ollama.${LOCAL_INTERNAL_DOMAIN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ollama-tls-cert
      hosts:
        - *domain

resources:
  requests:
    cpu: 10m
    memory: 226Mi
  limits:
    memory: 4Gi

persistentVolume:
  enabled: true
  storageClass: ${DEFAULT_STORAGE_CLASS}
  size: 50Gi
