---
service:
  ipFamilyPolicy: PreferDualStack

resources:
  requests:
    cpu: 3m
    memory: 64Mi
  limits:
    memory: 64Mi

webhook:
  resources:
    requests:
      cpu: 3m
      memory: 101Mi
    limits:
      memory: 101Mi

certController:
  resources:
    requests:
      cpu: 3m
      memory: 82Mi
    limits:
      memory: 82Mi
