---
service:
  ipFamilyPolicy: PreferDualStack

resources:
  requests:
    cpu: 6m
    memory: 71Mi
  limits:
    memory: 71Mi

webhook:
  resources:
    requests:
      cpu: 3m
      memory: 102Mi
    limits:
      memory: 102Mi

certController:
  resources:
    requests:
      cpu: 3m
      memory: 86Mi
    limits:
      memory: 86Mi
