---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: mealie-litellm
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mealie-litellm
        property: api-key
