---
updateStrategy:
  type: Recreate

expose:
  type: clusterIP
  tls:
    enabled: false

externalURL: https://registry.${PUBLIC_DOMAIN}

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: ${DEFAULT_STORAGE_CLASS}
      size: 10Gi
    jobservice:
      jobLog:
        storageClass: ${DEFAULT_STORAGE_CLASS}
        size: 5Gi
    database:
      storageClass: ${DEFAULT_STORAGE_CLASS}
      size: 5Gi
    redis:
      storageClass: ${DEFAULT_STORAGE_CLASS}
      size: 5Gi
    trivy:
      storageClass: ${DEFAULT_STORAGE_CLASS}
      size: 10Gi
  imageChartStorage:
    type: s3
    s3:
      region: fr-par
      regionendpoint: https://s3.fr-par.scw.cloud
      rootdirectory: /harbor
      bucket: scaleway-bucket-home-cluster-hochschule-burgenland-reg-ca4535c # TODO: this bucket must be changed
      existingSecret: scaleway-credentials

existingSecretAdminPassword: admin-password

logLevel: debug
metrics:
  enabled: true

cache:
  enabled: true
  expireHours: 24

existingSecretSecretKey: harbor-secrets

core:
  existingSecret: harbor-secrets
  existingXsrfSecret: harbor-secrets

jobservice:
  existingSecret: harbor-secrets

registry:
  existingSecret: harbor-secrets
  credentials:
    username: harbor_registry_user
    htpasswdString: "harbor_registry_user:$2y$10$ZFJ.a8gO7U.ypeWHT/HJnugnrSAOlzMP5Kc0e.nKBAtYkZGjsWKR."

trivy:
  severity: "LOW,MEDIUM,HIGH,CRITICAL"

# system settings manual configuration
# projectCreationRestriction: admin-only
# robotTokenExpiration: 365d

# cleanup manual configuration
# garbage collection:
#  schedule: daily
#  allow GC untagged artifacts & remove tag files: true
# log rotation:
#  schedule: daily
#  keepDays: 7
#  event types: all

# interrogtation services manual configuration
# vulnerability:
#  schedule: daily
