---
resources:
  requests:
    cpu: 78m
    memory: 364Mi
  limits:
    memory: 364Mi

ceph-csi-operator:
  controllerManager:
    manager:
      resources:
        requests:
          cpu: 3m
          memory: 72Mi
        limits:
          memory: 72Mi
