---
role: Agent

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: false
    address: 0.0.0.0:8686
    playground: true
  sources:
    k8s:
      type: kubernetes_logs
      ignore_older_secs: 600
      oldest_first: false
      read_from: end
      use_apiserver_cache: true
      namespace_annotation_fields:
        namespace_labels: ""
      node_annotation_fields:
        node_labels: ""
      pod_annotation_fields:
        container_id: ""
        container_image_id: ""
        pod_annotations: ""
        pod_ip: ""
        pod_ips: ""
        pod_node_name: ""
        pod_owner: ""
        pod_uid: ""
    internal_metrics:
      type: internal_metrics
  transforms:
    parser:
      type: remap
      inputs:
        - k8s
      source: |
        if exists(.kubernetes.pod_labels) {
          new_labels = {}
          for_each(object!(.kubernetes.pod_labels)) -> |key, value| {
              if starts_with(key, "app.kubernetes.io/") {
                  new_labels = set!(new_labels, [key], value)
              }
          }
          .kubernetes.pod_labels = new_labels
        }
        .log = parse_json(.message) ?? .message
        .log = strip_ansi_escape_codes!(string!(.log))
        del(.message)
        del(.kubernetes.pod_annotations)
  sinks:
    exporter:
      type: prometheus_exporter
      address: 0.0.0.0:9090
      inputs:
        - internal_metrics
    vlogs:
      type: elasticsearch
      endpoints:
        - http://victoria-logs-server:9428/insert/elasticsearch/
      inputs:
        - parser
      mode: bulk
      api_version: v8
      compression: gzip
      healthcheck:
        enabled: false
      buffer:
        type: disk
        when_full: drop_newest
        max_size: 1073741824
      request:
        headers:
          VL-Time-Field: timestamp
          VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace,kubernetes.pod_labels.app.kubernetes.io/name
          VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
          AccountID: "0"
          ProjectID: "0"

containerPorts:
  - name: prom-exporter
    containerPort: 9090
    protocol: TCP

service:
  ipFamilyPolicy: PreferDualStack

persistence:
  enabled: false
  hostPath:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 768Mi
  limits:
    memory: 768Mi
