---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-zoocode-apikey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: qdrant-zoocode-apikey
  data:
    - secretKey: api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: qdrant-zoocode
        property: api-key
    - secretKey: read-only-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: qdrant-zoocode
        property: read-only-api-key
