---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name vault-auth
spec:
  provider:
    vault:
      server: https://vault.platform.muehlbachler.io:8200
      path: kubernetes-hochschule-burgenland-cluster
      version: v2
      auth:
        appRole:
          path: approle
          roleId: d38e1aa3-307e-9341-2bb2-c26f00213298
          secretRef:
            namespace: external-secrets
            name: *name
            key: secret-id
