---
grafana:
  enabled: true

admissionController:
  rbac: &extraRbacResources
    clusterRole:
      extraResources:
        - apiGroups:
            - gateway.networking.k8s.io
          resources:
            - httproutes
            - listenersets
          verbs:
            - get
            - list
            - watch
  container:
    resources:
      requests:
        cpu: 8m
        memory: 128Mi
      limits:
        memory: 128Mi

backgroundController:
  rbac: *extraRbacResources
  resources:
    requests:
      cpu: 7m
      memory: 192Mi
    limits:
      memory: 512Mi

cleanupController:
  rbac: *extraRbacResources
  resources:
    requests:
      cpu: 9m
      memory: 56Mi
    limits:
      memory: 56Mi

reportsController:
  rbac: *extraRbacResources
  resources:
    requests:
      cpu: 4m
      memory: 104Mi
    limits:
      memory: 104Mi
