---
grafana:
  enabled: true

admissionController:
  container:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 128Mi

backgroundController:
  resources:
    requests:
      cpu: 10m
      memory: 192Mi
    limits:
      memory: 192Mi

cleanupController:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

reportsController:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
