---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.2.0/charts/library/common/values.schema.json
global:
  alwaysAppendIdentifierToResourceName: true

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    serviceAccount:
      identifier: gatus
    initContainers:
      init-gatus-sidecar:
        image:
          repository: alpine
          tag: 3.23
          pullPolicy: IfNotPresent
        command:
          - touch
          - /config/gatus-sidecar.yaml
        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 50m
            memory: 8Mi
    containers:
      gatus:
        image:
          repository: ghcr.io/twin/gatus
          pullPolicy: IfNotPresent
          tag: v5.35.0

        env:
          - name: GATUS_CONFIG_PATH
            value: /config
          - name: GATUS_DELAY_START_SECONDS
            value: "5"
        envFrom:
          - secretRef:
              name: gatus-ntfy

        resources:
          requests:
            cpu: 10m
            memory: 138Mi
          limits:
            memory: 138Mi

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

      gatus-sidecar:
        image:
          repository: ghcr.io/home-operations/gatus-sidecar
          pullPolicy: IfNotPresent
          tag: 0.0.14
        args:
          - --enable-httproute
          - --enable-ingress
          - --enable-service
          - --default-interval=5m
          - --output=/config/gatus-sidecar.yaml
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 64Mi

serviceAccount:
  gatus: {}

service:
  gatus:
    controller: main
    ipFamilyPolicy: PreferDualStack
    ports:
      http:
        port: 8080

ingress:
  gatus:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "${PUBLIC_CLUSTER_ISSUER}"
      external-dns.alpha.kubernetes.io/provider: public
      external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: &domain status.${LOCAL_HOME_DOMAIN}
        paths:
          - path: /
            pathType: ImplementationSpecific
            service:
              identifier: gatus
              port: 8080
    tls:
      - secretName: gatus-tls-cert
        hosts:
          - *domain

route:
  gatus:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/provider: public
      external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
    hostnames:
      - &domain status.${LOCAL_HOME_DOMAIN}
    parentRefs:
      - kind: ListenerSet
        name: gatus-listeners
        namespace: ${APPLICATION_NAMESPACE}
    rules:
      - backendRefs:
          - identifier: gatus
            port: 8080
        matches:
          - path:
              type: PathPrefix
              value: /
# rawResources:
#   gatus-listeners:
#     apiVersion: gateway.networking.k8s.io/v1
#     kind: ListenerSet
#     annotations:
#       cert-manager.io/cluster-issuer: "${PUBLIC_CLUSTER_ISSUER}"
#     spec:
#       parentRef:
#         group: gateway.networking.k8s.io
#         kind: Gateway
#         name: kgateway-gateway
#         namespace: kgateway
#       listeners:
#         - allowedRoutes:
#             namespaces:
#               from: Same
#           hostname: *domain
#           name: https-gatus
#           port: 443
#           protocol: HTTPS
#           tls:
#             certificateRefs:
#               - kind: Secret
#                 name: gatus-tls-cert
#             mode: Terminate

persistence:
  data:
    enabled: true
    storageClass: ${DEFAULT_STORAGE_CLASS}
    accessMode: ReadWriteOnce
    size: 200Mi
    retain: false
    globalMounts:
      - path: /data
  config:
    enabled: true
    type: emptyDir
  config-file:
    enabled: true
    type: configMap
    name: gatus-config
    globalMounts:
      - path: /config/config.yaml
        subPath: config.yaml
