---
rollOutCiliumPods: true

ipam:
  mode: kubernetes
ipv6:
  enabled: true

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

k8sServiceHost: 127.0.0.1
k8sServicePort: ${K8S_SERVICE_PORT:-7445}

k8sClientRateLimit:
  qps: 30
  burst: 60

l2announcements:
  enabled: false
externalIPs:
  enabled: false

cgroup:
  autoMount:
    enabled: ${CILIUM_CGROUP_AUTO_MOUNT_ENABLED:-false}
  hostRoot: ${CILIUM_CGROUP_HOST_ROOT:-/sys/fs/cgroup}

bpf:
  masquerade: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

prometheus:
  enabled: true

resources:
  requests:
    cpu: 49m
    memory: 1174Mi
  limits:
    memory: 2048Mi

operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 218Mi
    limits:
      memory: 218Mi

envoy:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      memory: 192Mi

preflight:
  enabled: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cluster-issuer-muehlbachler-xyz
        external-dns.alpha.kubernetes.io/provider: public
        external-dns.alpha.kubernetes.io/target: 178.63.69.250,2a01:4f8:121:14e2:100:3:3:1
        traefik.ingress.kubernetes.io/router.tls: "true"
      className: traefik
      hosts:
        - hubble.hochschule-burgenland.muehlbachler.xyz
      tls:
        - secretName: hubble-ui-tls
          hosts:
            - hubble.hochschule-burgenland.muehlbachler.xyz
