---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: kgateway-gateway-external-service-parameters
spec:
  kube:
    service:
      type: LoadBalancer
      loadBalancerClass: "${KGATEWAY_EXTERNAL_LB_CLASS}"
      extraAnnotations:
        ${KGATEWAY_EXTERNAL_IP_ANNOTATION}: "${KGATEWAY_EXTERNAL_IP}"
        gatus.home-operations.com/enabled: "true"
      extraLabels:
        loadbalancer/pool: l2
    serviceOverlay:
      spec:
        ipFamilyPolicy: PreferDualStack
        externalTrafficPolicy: Local
    envoyContainer:
      resources:
        limits:
          memory: 145Mi
        requests:
          cpu: 12m
          memory: 145Mi
