---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.2.0/charts/library/common/values.schema.json
controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      config-init:
        image:
          repository: alpine
          tag: 3.23
          pullPolicy: IfNotPresent

        command:
          - cp
          - /config/config.json
          - /etc/picoclaw/config.json

        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 50m
            memory: 8Mi
    containers:
      server:
        image:
          repository: ghcr.io/sipeed/picoclaw
          pullPolicy: IfNotPresent
          tag: v0.2.6

        args:
          - gateway

        env:
          - name: PICOCLAW_CONFIG
            value: /etc/picoclaw/config.json
          - name: TZ
            value: Etc/UTC
        envFrom:
          - secretRef:
              name: bot-opsbot-picoclaw-secrets-env

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 18790
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probe

        resources:
          requests:
            cpu: 5m
            memory: 24Mi
          limits:
            memory: 64Mi

service:
  bot-opsbot-picoclaw:
    controller: main
    annotations:
      gatus.home-operations.com/enabled: "true"
    ipFamilyPolicy: PreferDualStack
    ports:
      gateway:
        port: 18790

persistence:
  workspace:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ${DEFAULT_STORAGE_CLASS}
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      main:
        server:
          - path: /workspace
  config:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /etc/picoclaw
  configmap:
    enabled: true
    type: configMap
    name: bot-opsbot-picoclaw-config
    defaultMode: 511
    advancedMounts:
      main:
        config-init:
          - path: /config
