---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: mikrotik-switch-snmp
spec:
  jobName: mikrotik-switch-snmp
  targetEndpoints:
    - targets:
        - 10.0.10.1
        - 10.0.10.2
      interval: 5m
      scrapeTimeout: 30s
      params:
        module:
          - mikrotik
        auth:
          - mikrotik_v3
      relabelConfigs:
        - sourceLabels:
            - __address__
          targetLabel: __param_target
        - sourceLabels:
            - __param_target
          targetLabel: instance
        - targetLabel: __address__
          replacement: prometheus-snmp-exporter.prometheus-snmp-exporter:9116
