apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vault-auth
data:
    secret-id: ENC[AES256_GCM,data:YlfPqbTXou/pe4YmtyZsHG4K1bMi9lzxJIGiPhxr9wvbFkeCaL+0D4cjZ60LyHDb,iv:8z658lMpY5y7bRoFhldzrFvpvQrBLcW2vf7WR/+DZlc=,tag:XOwyyS8Q/VfIpGgxfDf+3A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-08-03T12:11:30Z"
          enc: CiQA9PdEcADtBcBkoMip+7B5WkzU6etCRRmEPAYTElasmNtziM4SSQA2N6cCXyGpTLRfiZ4MeIxuX3ZZp8KWfpFx06D91btFzDCifgYv4sFfR75RXcoUpYn9xT0zuzQ/6kDiu6N+Jn8Qhq8lFy5VfMw=
          resource_id: projects/tuxnet-385112/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
    lastmodified: "2026-08-03T12:11:30Z"
    mac: ENC[AES256_GCM,data:wcrNvTJDaObcGkzTkr7h7B3UzM21C1jirENTiemBEcZaryXgigfVs5WdXCsogqp7HBMx5BAOaPFRXW7zGlvUAYIFAvLKatBDdZ8qH3zHcXilo97+Onfbo3RkUImlPQhrYU8I1SS7P/eMiIi0ZXsVRdPPJLXrGZ7BfyJ9PEeUa2A=,iv:/DICXRyzbWTkaNhRYdDOimsChKBMduyAS+KJ6C1KTzQ=,tag:ymRaCZzU2+u46sXtYfsvFA==,type:str]
    version: 3.13.3
