---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bot-opsbot-picoclaw-secrets-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: bot-opsbot-picoclaw-secrets-env
  data:
    - secretKey: GITHUB_MCP_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-mcp-servers
        property: github
    - secretKey: GEMINI_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-providers
        property: gemini
    - secretKey: OPENAI_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-providers
        property: openai
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-providers
        property: anthropic
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-channels
        property: discord
