---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bot-opsbot-picoclaw-secrets-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: bot-opsbot-picoclaw-secrets-config
    template:
      engineVersion: v2
      data:
        security.yml: |
          model_list:
            gemini-flash:0:
              api_keys:
                - {{ .gemini_api_key }}
            gpt-nano:0:
              api_keys:
                - {{ .openai_api_key }}
            gpt-mini:0:
              api_keys:
                - {{ .openai_api_key }}
            claude-haiku:0:
              api_keys:
                - {{ .anthropic_api_key }}
          channels:
            discord:
              token: {{ .discord_token }}
  data:
    - secretKey: gemini_api_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-providers
        property: gemini
    - secretKey: openai_api_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-providers
        property: openai
    - secretKey: anthropic_api_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-providers
        property: anthropic
    - secretKey: discord_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: agents-bot-opsbot-channels
        property: discord
