---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../common/applications/omada-controller/
  - ../../../common/applications/influxdb/
  - ./external-services/
  - ./homepage/
  - ./litellm/
  - ./ollama/
  - ./immich/
  - ./librechat/
  - ./mealie/
  - ./agents/
