---
fullnameOverride: emqx

envFromSecret: home-assistant-emqx

replicaCount: 1

podAnnotations:
  reloader.stakater.com/auto: "true"

emqxConfig:
  EMQX_LISTENERS__TCP__DEFAULT__BIND: "[::]:1883"
  EMQX_LISTENERS__SSL__DEFAULT__BIND: "[::]:8883"
  EMQX_LISTENERS__WS__DEFAULT__BIND: "[::]:8083"
  EMQX_LISTENERS__WSS__DEFAULT__BIND: "[::]:8084"

service:
  annotations:
    gatus.home-operations.com/enabled: "true"

persistence:
  enabled: true
  storageClassName: ${DEFAULT_STORAGE_CLASS}
  accessMode: ReadWriteOnce
  size: 512Mi

ssl:
  enabled: true
  useExisting: true
  existingName: emqx-tls

resources:
  requests:
    cpu: 6m
    memory: 375Mi
  limits:
    memory: 375Mi
