---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-scripts
data:
  backup_restore.sh: |
    #!/bin/sh
    set -eu

    apk --no-cache add bash libarchive-tools s3cmd

    "$${REPO_PATH}/lifecycle/backup_restore.sh" "$${DATA_PATH}"
  sync_configuration.sh: |
    #!/bin/sh
    set -eu

    IGNORE_RETURN_VALUES="${1:-false}"

    apk --no-cache add bash libarchive-tools sops

    "$${REPO_PATH}/lifecycle/sops.sh" d "$${REPO_PATH}"

    "$${REPO_PATH}/lifecycle/configuration.sh" "$${DATA_PATH}" "$${REPO_PATH}" ${SITE} "$${STATE_PATH}" "$${IGNORE_RETURN_VALUES}"
    "$${REPO_PATH}/lifecycle/prepare.sh" "$${DATA_PATH}" "$${REPO_PATH}" "$${STATE_PATH}" "$${IGNORE_RETURN_VALUES}"
  dockerenv: |
    # TODO: remove once https://github.com/home-assistant/core/issues/127966 (PR: https://github.com/home-assistant/core/pull/132404) is fixed
