---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-ntfy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: home-assistant-ntfy
    template:
      engineVersion: v2
      data:
        NTFY_AUTH_TOKEN: "Bearer {{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: home-assistant-home-assistant-ntfy
        property: token
