---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: home-assistant-oidc
  data:
    - secretKey: OIDC_WELL_KNOWN_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: well_known_url
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: home-assistant-home-assistant-oidc
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: home-assistant-home-assistant-oidc
        property: client_secret
