---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-5.0.0/charts/library/common/values.schema.json
global:
  alwaysAppendIdentifierToResourceName: true

controllers:
  main:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      home-assistant:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          pullPolicy: IfNotPresent
          tag: 2026.4.4

        env:
          - name: TZ
            value: UTC
          - name: DATA_PATH
            value: /config
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /gcp-credentials/credentials.json
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: home-assistant-gcp-credentials
                key: credentials.json
          - name: POSTGRESQL_URI
            valueFrom:
              secretKeyRef:
                name: home-assistant-postgresql-app
                key: uri

        envFrom:
          - secretRef:
              name: home-assistant-backup
          - configMapRef:
              name: home-assistant-git

        resources:
          requests:
            cpu: 14m
            memory: 920Mi
          limits:
            memory: 1538Mi

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

    initContainers:
      backup-restore:
        image:
          repository: alpine
          tag: 3.23
          pullPolicy: IfNotPresent
        command:
          - /scripts/backup_restore.sh
          - "true"
        envFrom:
          - secretRef:
              name: home-assistant-backup
          - configMapRef:
              name: home-assistant-git
        env:
          - name: DATA_PATH
            value: /config
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /gcp-credentials/credentials.json
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: home-assistant-gcp-credentials
                key: credentials.json
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 512Mi

service:
  home-assistant:
    controller: main
    annotations:
      gatus.home-operations.com/enabled: "true"
    ipFamilyPolicy: PreferDualStack
    ports:
      http:
        port: 8123

route:
  home-assistant-internal:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/provider: internal
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: ListenerSet
        namespace: ${APPLICATION_NAMESPACE}
        name: home-assistant-home-assistant-internal-listeners
    hostnames:
      - &internal_domain manage.iot.${LOCAL_INTERNAL_DOMAIN}
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: home-assistant
            port: 8123
  home-assistant-external:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/provider: public
      external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: ListenerSet
        namespace: ${APPLICATION_NAMESPACE}
        name: home-assistant-home-assistant-external-listeners
    hostnames:
      - &external_domain jarvis.${LOCAL_HOME_DOMAIN}
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: home-assistant
            port: 8123
rawResources:
  internal-listeners:
    manifest:
      apiVersion: gateway.networking.k8s.io/v1
      kind: ListenerSet
      metadata:
        annotations:
          cert-manager.io/cluster-issuer: "${INTERNAL_CLUSTER_ISSUER}"
      spec:
        parentRef:
          name: kgateway-gateway-internal
          namespace: kgateway
        listeners:
          - name: https-home-assistant-internal
            protocol: HTTPS
            port: 443
            hostname: *internal_domain
            tls:
              mode: Terminate
              certificateRefs:
                - name: home-assistant-home-assistant-internal-tls-cert
  external-listeners:
    manifest:
      apiVersion: gateway.networking.k8s.io/v1
      kind: ListenerSet
      annotations:
        cert-manager.io/cluster-issuer: "${PUBLIC_CLUSTER_ISSUER}"
      spec:
        parentRef:
          name: kgateway-gateway
          namespace: kgateway
        listeners:
          - name: https-home-assistant-external
            protocol: HTTPS
            port: 443
            hostname: *external_domain
            tls:
              mode: Terminate
              certificateRefs:
                - name: home-assistant-home-assistant-external-tls-cert

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ${DEFAULT_STORAGE_CLASS}
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
  scripts:
    enabled: true
    type: configMap
    name: home-assistant-scripts
    defaultMode: 0o777
  gcp-credentials:
    enabled: true
    type: secret
    name: home-assistant-gcp-credentials
    globalMounts:
      - path: /gcp-credentials
        readOnly: true
  # TODO: remove once https://github.com/home-assistant/core/issues/127966 (PR: https://github.com/home-assistant/core/pull/132404) is fixed
  dockerenv:
    enabled: true
    type: configMap
    name: home-assistant-scripts
    advancedMounts:
      main:
        home-assistant:
          - path: /.dockerenv
            subPath: dockerenv
