---
driver:
  enabled: false
toolkit:
  enabled: false
hostPaths:
  driverInstallDir: /usr/local

operator:
  resources:
    limits:
      memory: 195Mi
    requests:
      cpu: 3m
      memory: 195Mi

node-feature-discovery:
  gc:
    resources:
      limits:
        memory: 41Mi
      requests:
        cpu: 3m
        memory: 41Mi
  master:
    resources:
      limits:
        memory: 63Mi
      requests:
        cpu: 3m
        memory: 63Mi
  worker:
    resources:
      limits:
        memory: 60Mi
      requests:
        cpu: 3m
        memory: 60Mi

gfd:
  resources:
    requests:
      cpu: 3m
      memory: 90Mi
    limits:
      memory: 90Mi

dcgmExporter:
  resources:
    requests:
      cpu: 11m
      memory: 578Mi
    limits:
      memory: 578Mi

validator:
  resources:
    requests:
      cpu: 3m
      memory: 8Mi
    limits:
      # this is required for startup
      memory: 32Mi

devicePlugin:
  resources:
    requests:
      cpu: 3m
      memory: 52Mi
    limits:
      memory: 52Mi
  config:
    name: device-plugin-config
    create: true
    default: default
    data:
      default: |-
        version: v1
        flags:
          migStrategy: "none"
          failOnInitError: false
          nvidiaDriverRoot: "/"
          plugin:
            passDeviceSpecs: false
            deviceListStrategy:
              - envvar
            deviceIDStrategy: uuid
        sharing:
          timeSlicing:
            renameByDefault: false
            failRequestsGreaterThanOne: true
            resources:
              - name: nvidia.com/gpu
                replicas: 10
          # mps:
          #   resources:
          #     - name: nvidia.com/gpu
          #       replicas: 10
