---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: percona-mongodb-backup-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: percona-mongodb-backup-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: percona-mongodb-scaleway
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: percona-mongodb-scaleway
        property: secret_key
