---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ./service.yaml
  - ./endpointslice.yaml
  - ./gateway.yaml
  - ./external-secret-omada-controller-mongodb-user.yaml
  - ./external-secret-omada-controller-mongodb-secrets.yaml
  - ./external-secret-percona-mongodb-backup-credentials.yaml
  - ./mongodb.yaml
