---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: zot-config
    template:
      engineVersion: v2
      data:
        config.yaml: |-
          http:
            address: 0.0.0.0
            port: 5000
            realm: zot
            readTimeout: 60s
            writeTimeout: 60s
            externalUrl: https://registry.${PUBLIC_DOMAIN}
            auth:
              apikey: true
              openid:
                providers:
                  oidc:
                    name: GitHub
                    issuer: https://auth.${PUBLIC_DOMAIN}/api/dex
                    credentialsFile: /etc/zot/dex-credentials.json
                    claimMapping:
                      username: preferred_username
                      groups: groups
                    scopes:
                      - openid
                      - profile
                      - email
                      - groups
                      - offline_access
            accessControl:
              repositories:
                "**":
                  policies:
                    - users:
                        - muhlba91
                      actions:
                        - read
                        - create
                        - update
                        - delete
                  defaultPolicy: []
          log:
            level: warn
          extensions:
            ui:
              enable: true
            scrub:
              enable: true
              interval: 24h
            search:
              enable: true
              # cve:
              #   updateInterval: 24h
              #   trivy:
              #     sbom:
              #       enable: true
              #       format: spdx-json
          storage:
            rootDirectory: /var/lib/registry
            # remoteCache: true
            dedupe: false
            storageDriver:
              name: s3
              rootdirectory: /zot
              region: fr-par
              regionendpoint: https://s3.fr-par.scw.cloud
              bucket: {{ .bucket }}
              secure: true
            # cacheDriver:
            #   name: redis
            #   url: redis://zot-valkey:6379
            #   keyprefix: zot
  data:
    - secretKey: bucket
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: registry-scaleway
        property: bucket
