---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: dex-config
    template:
      engineVersion: v2
      data:
        credentials.json: |-
          {
            "clientid": "registry",
            "clientsecret": "{{ .registry_client_secret }}"
          }
  data:
    - secretKey: registry_client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dex-registry
        property: client_secret
