---
operatorConfig:
  driverSpecDefaults:
    nodePlugin:
      priorityClassName: system-node-critical
    controllerPlugin:
      priorityClassName: system-cluster-critical
      replicas: 1

drivers:
  rbd:
    enabled: true
    name: rook-ceph.rbd.csi.ceph.com
    controllerPlugin:
      priorityClassName: system-cluster-critical
      resources:
        attacher:
          requests:
            cpu: 5m
            memory: 96Mi
          limits:
            memory: 96Mi
        omapGenerator:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 1Gi
        plugin:
          requests:
            cpu: 5m
            memory: 56Mi
          limits:
            memory: 96Mi
        provisioner:
          requests:
            cpu: 5m
            memory: 96Mi
          limits:
            memory: 96Mi
        resizer:
          requests:
            cpu: 5m
            memory: 96Mi
          limits:
            memory: 96Mi
        snapshotter:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 100Mi
        addons: {}
        liveness: {}
        logRotator:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            memory: 16Mi
    nodePlugin:
      priorityClassName: system-cluster-critical
      resources:
        plugin:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            memory: 128Mi
        registrar:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 32Mi
        addons: {}
        liveness: {}
        logRotator:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            memory: 16Mi

  cephfs:
    enabled: true
    name: rook-ceph.cephfs.csi.ceph.com
    controllerPlugin:
      resources:
        attacher:
          requests:
            cpu: 5m
            memory: 24Mi
          limits:
            memory: 64Mi
        plugin:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            memory: 64Mi
        provisioner:
          requests:
            cpu: 5m
            memory: 24Mi
          limits:
            memory: 64Mi
        resizer:
          requests:
            cpu: 5m
            memory: 24Mi
          limits:
            memory: 64Mi
        snapshotter:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            memory: 64Mi
        omapGenerator: {}
        addons: {}
        liveness: {}
        logRotator:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            memory: 16Mi
    nodePlugin:
      resources:
        plugin:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            memory: 64Mi
        registrar:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 32Mi
        addons: {}
        liveness: {}
        logRotator:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            memory: 16Mi

  nfs:
    enabled: false
    name: rook-ceph.nfs.csi.ceph.com
  nvmeof:
    enabled: false
    name: rook-ceph.nvmeof.csi.ceph.com
