---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: kgateway-gateway-internal-listeners
  namespace: kgateway
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kgateway-gateway-internal
    namespace: kgateway
  listeners:
    - name: https-443
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
    - name: https-443-passthrough-muehlbachler-io
      protocol: TLS
      port: 443
      hostname: "*.muehlbachler.io"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - name: https-443-passthrough-muehlbachler-xyz
      protocol: TLS
      port: 443
      hostname: "*.muehlbachler.xyz"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
