---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: k8smeta-config
  namespace: falco
spec:
  config:
    plugins:
      - name: k8smeta
        library_path: k8smeta.so
        init_config:
          collectorHostname: metacollector
          collectorPort: 45000
          nodeName: $${FALCO_K8S_NODE_NAME}
  priority: 55
