---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-snmp-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: snmp-config
    template:
      engineVersion: v2
      data:
        snmp.yml: |
          ---
          auths:
            mikrotik_v3:
              version: 3
              auth_protocol: SHA
              username: {{ .mikrotik_snmp_username }}
              password: "{{ .mikrotik_snmp_auth_password }}"
              priv_protocol: AES
              priv_password: "{{ .mikrotik_snmp_priv_password }}"
              security_level: authPriv
          modules:
            mikrotik:
              walks:
                - 1.3.6.1.2.1.1          # System: Name, Location, Uptime
                - 1.3.6.1.2.1.2          # Interfaces: Standard stats (bits in/out)
                - 1.3.6.1.2.1.31.1.1     # ifXTable: CRITICAL for 10G+. Provides 64-bit counters so your graphs don't reset at 4Gbps.
                - 1.3.6.1.4.1.14988.1.1  # MikroTik Health: Voltage, Temperature, Fan Speed
                - 1.3.6.1.2.1.17         # Bridge MIB: Useful if you want to see MAC address tables/STP status
                - 1.3.6.1.2.1.25.1       # Host Resources: CPU and Memory usage
  data:
    - secretKey: mikrotik_snmp_username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mikrotik-snmp
        property: username
    - secretKey: mikrotik_snmp_auth_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mikrotik-snmp
        property: auth_password
    - secretKey: mikrotik_snmp_priv_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mikrotik-snmp
        property: priv_password
