---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-snmp-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: snmp-config
    template:
      engineVersion: v2
      data:
        snmp.yml: |
          auths:
            mikrotik_v3:
              version: 3
              auth_protocol: SHA
              username: {{ .mikrotik_snmp_username }}
              password: "{{ .mikrotik_snmp_auth_password }}"
              priv_protocol: AES
              priv_password: "{{ .mikrotik_snmp_priv_password }}"
              security_level: authPriv
  data:
    - secretKey: mikrotik_snmp_username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mikrotik-snmp
        property: username
    - secretKey: mikrotik_snmp_auth_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mikrotik-snmp
        property: auth_password
    - secretKey: mikrotik_snmp_priv_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mikrotik-snmp
        property: priv_password
