---
resources:
  requests:
    cpu: 8m
    memory: 301Mi
  limits:
    memory: 301Mi

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  extraSecretRef: velero-backup-credentials

configuration:
  backupStorageLocation: []
  volumeSnapshotLocation: []
  defaultBackupStorageLocation: scaleway

deployNodeAgent: true
nodeAgent:
  resources:
    requests:
      cpu: 3m
      memory: 114Mi
    limits:
      memory: 114Mi
