---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-5.0.0/charts/library/common/values.schema.json
global:
  alwaysAppendIdentifierToResourceName: true

defaultPodOptions:
  automountServiceAccountToken: true

controllers:
  main:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      zwave-js:
        image:
          repository: zwavejs/zwave-js-ui
          pullPolicy: IfNotPresent
          tag: 11.17.0@sha256:79827886d44929105b625b07ce9870e739502d8b421bff5b11a4c17f811fb577

        envFrom:
          - secretRef:
              name: zwave-js-network

        env:
          - name: TZ
            value: UTC
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: zwave-js-session
                key: secret

        securityContext:
          privileged: true

        resources:
          requests:
            cpu: 10m
            memory: 207Mi
          limits:
            memory: 207Mi

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

  backup:
    type: cronjob
    serviceAccount:
      identifier: home-assistant-zwave
    cronjob:
      concurrencyPolicy: Replace
      schedule: 0 0 * * *
      successfulJobsHistory: 3
      failedJobsHistory: 3
      startingDeadlineSeconds: 30
      backoffLimit: 2
    pod:
      restartPolicy: OnFailure
    containers:
      backup:
        image:
          repository: alpine
          tag: 3.23
          pullPolicy: IfNotPresent
        command:
          - /scripts/backup_restore.sh
        envFrom:
          - secretRef:
              name: zwave-js-backup
        resources:
          requests:
            cpu: 14m
            memory: 100Mi
          limits:
            memory: 100Mi

serviceAccount:
  home-assistant-zwave: {}

service:
  zwave-js:
    controller: main
    annotations:
      gatus.home-operations.com/enabled: "true"
    ipFamilyPolicy: PreferDualStack
    ports:
      http:
        port: 8091
      ws:
        enabled: true
        port: 3000

route:
  zwave:
    enabled: true
    kind: HTTPRoute
    annotations:
      external-dns.alpha.kubernetes.io/provider: internal
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: ListenerSet
        namespace: ${APPLICATION_NAMESPACE}
        name: home-assistant-zwave-listeners
    hostnames:
      - &domain zwave.iot.${LOCAL_INTERNAL_DOMAIN}
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: zwave-js
            port: 8091
rawResources:
  listeners:
    manifest:
      apiVersion: gateway.networking.k8s.io/v1
      kind: ListenerSet
      metadata:
        annotations:
          cert-manager.io/cluster-issuer: "${INTERNAL_CLUSTER_ISSUER}"
      spec:
        parentRef:
          name: kgateway-gateway-internal
          namespace: kgateway
        listeners:
          - name: https-home-assistant-zwave
            protocol: HTTPS
            port: 443
            hostname: *domain
            tls:
              mode: Terminate
              certificateRefs:
                - name: home-assistant-zwave-tls-cert

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ${DEFAULT_STORAGE_CLASS}
    accessMode: ReadWriteOnce
    size: 512Mi
    retain: false
    advancedMounts:
      main:
        zwave-js:
          - path: /usr/src/app/store
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev
    hostPathType: Directory
    advancedMounts:
      main:
        zwave-js:
          - path: /dev
  scripts:
    enabled: true
    type: configMap
    name: zwave-js-scripts
    defaultMode: 511
    advancedMounts:
      backup:
        backup:
          - path: /scripts
