---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
data:
  librechat.yaml: |
    version: 1.2.8

    cache: true

    fileStrategy: s3

    fileConfig:
      endpoints:
        default:
          fileSizeLimit: 10
          totalSizeLimit: 100
      serverFileSizeLimit: 100
      avatarSizeLimit: 4

    rateLimits:
      fileUploads:
        ipMax: 100
        ipWindowInMinutes: 60
        userMax: 50
        userWindowInMinutes: 60

    registration:
      socialLogins:
        - openid
      allowedDomains:
        - "muehlbachler.io"

    transactions:
      enabled: true

    memory:
      disabled: false
      messageWindowSize: 8
      validKeys:
        - user_preferences
        - learned_facts
        - project_details
        - tech_stack
      agent:
        provider: LiteLLM
        model: gemini-3.1-flash-lite-preview
        model_parameters:
          temperature: 0.1
          max_tokens: 1000
          top_p: 0.1

    ocr:
      mistralModel: mistral-ocr-latest
      baseURL: http://litellm.litellm:4000/v1
      apiKey: "$${LITELLM_API_KEY}"
      strategy: mistral_ocr

    webSearch:
      searchProvider: serper
      serperApiKey: "$${SERPER_API_KEY}"
      rerankerType: jina
      jinaApiKey: "$${JINA_API_KEY}"
      safeSearch: 0

    mcpServers:
      memory:
        command: npx
        args:
          - "@modelcontextprotocol/server-memory"
        startup: false
        initTimeout: 15000
      home-assistant:
        type: streamable-http
        url: https://jarvis.${LOCAL_HOME_DOMAIN}/api/mcp
        oauth:
          authorization_url: https://jarvis.${LOCAL_HOME_DOMAIN}/auth/authorize
          token_url: https://jarvis.${LOCAL_HOME_DOMAIN}/auth/token
          client_id: https://gpt.${HOME_DOMAIN}
          redirect_uri: https://gpt.${HOME_DOMAIN}/api/mcp/home-assistant/oauth/callback
          scope: "read execute"
        startup: false
        initTimeout: 15000
      github:
        type: streamable-http
        url: "https://api.githubcopilot.com/mcp/"
        headers:
          Authorization: "Bearer {{PAT_TOKEN}}"
        customUserVars:
          PAT_TOKEN:
            title: "GitHub PAT Token"
            description: "GitHub Personal Access Token"
        startup: false
        initTimeout: 30000

    endpoints:
      agents:
        recursionLimit: 50
        maxRecursionLimit: 100
        disableBuilder: false
        maxCitations: 30
        maxCitationsPerFile: 7
        minRelevanceScore: 0.45
      custom:
        - name: LiteLLM
          modelDisplayLabel: Model Proxy
          apiKey:  user_provided
          baseURL: http://litellm.litellm:4000/v1
          iconURL: https://raw.githubusercontent.com/BerriAI/litellm/main/docs/my-docs/static/img/litellm_logo.png
          models:
            default:
              - qwen3.5
              - gemma4
            fetch: true
          titleConvo: true
          titleModel: gemini-3.1-flash-lite-preview
          titleMethod: completion
