---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-mongodb-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: librechat-mongodb-user
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: librechat-mongodb-user
        property: password
