---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-mongodb-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: librechat-mongodb-user
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        uri: "mongodb://librechat:{{ .password }}@librechat-mongodb-rs0:27017/librechat?replicaSet=rs0&authSource=librechat"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: librechat-mongodb-user
        property: password
