---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.2.0/charts/library/common/values.schema.json
controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      server:
        image:
          repository: ghcr.io/github/github-mcp-server
          pullPolicy: IfNotPresent
          tag: v0.33.0

        args:
          - http

        envFrom:
          - configMapRef:
              name: github-mcp-server-env

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 8082
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probe

        resources:
          requests:
            cpu: 5m
            memory: 24Mi
          limits:
            memory: 96Mi

service:
  mcp-server-github:
    controller: main
    annotations:
      gatus.home-operations.com/enabled: "true"
    ipFamilyPolicy: PreferDualStack
    ports:
      http:
        port: 8082
