---
apiVersion: batch/v1
kind: Job
metadata:
  name: zwave-js-restore
  annotations:
    # recreate (= re-run) the Job when an immutable field such as the image changes
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  backoffLimit: 5
  template:
    spec:
      automountServiceAccountToken: true
      serviceAccountName: home-assistant-zwave
      restartPolicy: OnFailure
      containers:
        - name: backup
          image: alpine:3.24
          imagePullPolicy: IfNotPresent
          command:
            - /scripts/backup_restore.sh
          envFrom:
            - secretRef:
                name: zwave-js-backup
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 256Mi
      volumes:
        - name: scripts
          configMap:
            name: zwave-js-scripts
            defaultMode: 511
